project_name: helm-env
builds:
  - binary: ./bin/helm-env
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml