repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    exclude: charts/
  - id: check-merge-conflict
  - exclude: README.md
    id: end-of-file-fixer
  - exclude: README.md
    id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-added-large-files
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.11.0
  hooks:
    - id: helm-docs
      args:
        - --output-file=README.md
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
  - id: terraform_docs
    args:
      - --hook-config=--add-to-existing-file=true     # Boolean. true or false
      - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
  - id: terraform_tfsec
    args:
      - --args=--exclude-downloaded-modules
  # - id: terraform_providers_lock
  # - id: terrascan
  #   args:
  #     - --args=--non-recursive
  - id: terraform_validate
    exclude: infrastructure/modules/([^/]*)/[^/].+$
# - repo: https://github.com/bridgecrewio/checkov.git
#   rev: '2.3.33'
#   hooks:
#     - id: checkov
#       # verbose: true
#       args: [
#         # '--download-external-modules', 'true',
#         '--framework', 'terraform'
#       ]
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - id: hadolint-docker
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.13.0
  hooks:
  - id: commitizen
    stages:
    - commit-msg
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
  - id: go-fmt
  # - id: go-lint
  # - id: go-vet
  - id: go-mod-tidy
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.22.0
  hooks:
    - id: check-github-workflows
    - id: check-github-actions
