name: "set"
version: "0.0.6"
usage: "helm set install|upgrade"
description: |-
  This plugin provides a way to translate environment variables
  to helm values using set.
command: "./helm-set"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./helm-set.sh"
  update: "cd $HELM_PLUGIN_DIR; ./helm-set.sh"